
let SEARCH_DATA=[];
fetch('search-index.json').then(r=>r.json()).then(x=>SEARCH_DATA=x).catch(()=>{});
const q=document.querySelector('#siteSearch'), box=document.querySelector('#searchResults');
if(q&&box){
 q.addEventListener('input',()=>{
  const s=q.value.trim().toLowerCase();
  if(s.length<2){box.classList.remove('open');box.innerHTML='';return}
  const rows=SEARCH_DATA.filter(x=>(x.title+' '+x.chapter+' '+x.keywords).toLowerCase().includes(s)).slice(0,12);
  box.innerHTML=rows.map(x=>`<a class="searchItem" href="${x.url}"><b>${x.title}</b><small>${x.chapter}</small></a>`).join('');
  box.classList.toggle('open',rows.length>0);
 });
 document.addEventListener('click',e=>{if(!e.target.closest('.search'))box.classList.remove('open')})
}
document.querySelectorAll('.quizQ').forEach(q=>{
 q.querySelectorAll('button').forEach(b=>b.onclick=()=>{
  const f=q.querySelector('.feedback'); const ok=b.dataset.ok==='1';
  f.textContent=ok?'Correct ✓':'Try again — review the concept and visualization above.';
  f.style.color=ok?'#16805d':'#b66a11';
 });
});
document.querySelectorAll('[data-ohm]').forEach(v=>{
 const V=v.querySelector('[data-v]'),R=v.querySelector('[data-r]'),o=v.querySelector('[data-out]');
 const u=()=>{const a=(+V.value)/(+R.value);o.textContent=`Current I = ${a.toFixed(2)} A  (V=${V.value} V, R=${R.value} Ω)`}; V.oninput=u;R.oninput=u;u();
});
document.querySelectorAll('[data-ph]').forEach(v=>{
 const x=v.querySelector('input'),o=v.querySelector('[data-out]');
 const u=()=>{let n=+x.value, t=n<7?'Acidic':n>7?'Basic':'Neutral';o.textContent=`pH ${n}: ${t}`};x.oninput=u;u();
});
document.querySelectorAll('[data-energy]').forEach(v=>{
 const x=v.querySelector('input'),o=v.querySelector('[data-out]');
 const u=()=>{let e=+x.value; o.innerHTML=`Producer: ${e} units → Primary consumer: ${(e*.1).toFixed(0)} → Secondary consumer: ${(e*.01).toFixed(0)}`};x.oninput=u;u();
});
document.querySelectorAll('[data-balance]').forEach(v=>{
 const a=v.querySelector('[data-a]'),b=v.querySelector('[data-b]'),c=v.querySelector('[data-c]'),o=v.querySelector('[data-out]');
 const u=()=>{let lm=+a.value,lo=2*(+b.value),rm=+c.value,ro=+c.value;o.textContent=(lm===rm&&lo===ro)?'Balanced ✓ atoms match on both sides':`Left Mg ${lm}, O ${lo} · Right Mg ${rm}, O ${ro}`};[a,b,c].forEach(x=>x.oninput=u);u();
});

// ---------- V2 interactive labs ----------
document.querySelectorAll('[data-balance2]').forEach(v=>{
 const a=v.querySelector('[data-a]'),b=v.querySelector('[data-b]'),c=v.querySelector('[data-c]'),o=v.querySelector('[data-out]');
 const u=()=>{const lm=+a.value,lo=2*(+b.value),rm=+c.value,ro=+c.value;o.textContent=(lm===rm&&lo===ro)?`Balanced ✓ Mg ${lm} = ${rm}, O ${lo} = ${ro}`:`Left: Mg ${lm}, O ${lo} · Right: Mg ${rm}, O ${ro}`};[a,b,c].forEach(x=>x.oninput=u);u();
});
document.querySelectorAll('[data-reaction-lab]').forEach(v=>{const o=v.querySelector('[data-out]');v.querySelectorAll('button').forEach(b=>b.onclick=()=>{o.innerHTML=b.dataset.step==='0'?'Reactants are the starting substances.':b.dataset.step==='1'?'Bonds/arrangements change during the reaction; atoms are conserved.':'Products are new substances formed after the reaction.'})});
document.querySelectorAll('[data-corrosion]').forEach(v=>{const w=v.querySelector('[data-water]'),a=v.querySelector('[data-air]'),s=v.querySelector('[data-salt]'),m=v.querySelector('[data-meter]'),o=v.querySelector('[data-out]');const u=()=>{let score=(w.checked?40:0)+(a.checked?40:0)+(s.checked?20:0);m.style.width=score+'%';o.textContent=score>=80?'High rusting tendency: moisture and oxygen are present.':score>=40?'Limited conditions for rusting.':'Rusting conditions are strongly reduced.'};[w,a,s].forEach(x=>x.onchange=u);u()});
document.querySelectorAll('[data-ph2]').forEach(v=>{const x=v.querySelector('[data-slider]'),n=v.querySelector('[data-num]'),o=v.querySelector('[data-out]');const u=()=>{let p=+x.value;n.textContent=p;o.textContent=p<7?'Acidic — hydrogen ion effect dominates.':p>7?'Basic — hydroxide ion effect dominates.':'Neutral point on this school-level pH scale.'};x.oninput=u;u()});
document.querySelectorAll('[data-ion]').forEach(v=>{const stage=v.querySelector('[data-stage]'),o=v.querySelector('[data-out]');let ions=[];v.querySelectorAll('[data-ionv]').forEach(b=>b.onclick=()=>{ions.push(b.dataset.ionv);stage.innerHTML=ions.map(i=>`<span class="ionBubble">${i}</span>`).join('');o.textContent='Ions present: '+ions.join(', ')});});
document.querySelectorAll('[data-reactivity]').forEach(v=>{const order=['K','Ca','Mg','Al','Zn','Fe','Pb','H','Cu','Ag','Au'];v.querySelector('[data-check]').onclick=()=>{const a=v.querySelector('[data-m1]').value,b=v.querySelector('[data-m2]').value,o=v.querySelector('[data-out]');o.textContent=order.indexOf(a)<order.indexOf(b)?`${a} is higher in the selected series and can displace ${b} from a suitable compound.`:`${a} is not above ${b}; displacement is not predicted by this comparison.`}});
document.querySelectorAll('[data-electron]').forEach(v=>{v.querySelector('[data-transfer]').onclick=()=>{v.querySelector('[data-na]').textContent='Na⁺';v.querySelector('[data-cl]').textContent='Cl⁻';v.querySelector('[data-out]').textContent='Electron transfer creates oppositely charged ions; electrostatic attraction forms the ionic bond.'}});
document.querySelectorAll('[data-metal]').forEach(v=>{v.querySelector('[data-check]').onclick=()=>{const m=v.querySelector('[data-metal-select]').value,c=v.querySelector('[data-condition]').value,o=v.querySelector('[data-out]');o.textContent=`Compare ${m} under ${c}: use the reactivity series and the chapter observations to predict whether reaction is vigorous, slow or absent.`}});
document.querySelectorAll('[data-carbon]').forEach(v=>{const c=v.querySelector('[data-c]'),b=v.querySelector('[data-bond]'),chain=v.querySelector('[data-chain]'),o=v.querySelector('[data-out]');const u=()=>{let n=+c.value,s=b.value==='single'?'—':b.value==='double'?'=':'≡';chain.innerHTML=Array.from({length:n},(_,i)=>`<span class="cAtom">C</span>${i<n-1?`<span class="cBond">${s}</span>`:''}`).join('');o.textContent=`${n} carbon atom(s), ${b.value} C–C bond representation.`};c.oninput=u;b.onchange=u;u()});
document.querySelectorAll('[data-micelle]').forEach(v=>{v.querySelector('[data-start]').onclick=()=>{const h=v.querySelector('[data-heads]');h.innerHTML='';for(let i=0;i<12;i++){let d=document.createElement('span');d.className='soapDot';let ang=i*30*Math.PI/180;d.style.left=`calc(50% + ${Math.cos(ang)*75}px - 12px)`;d.style.top=`calc(50% + ${Math.sin(ang)*75}px - 12px)`;h.appendChild(d)}v.querySelector('[data-out]').textContent='Soap molecules surround oily dirt, forming a micelle that can be carried away in water.'}});
document.querySelectorAll('[data-carbon-reaction]').forEach(v=>{const o=v.querySelector('[data-out]');const m={combustion:'Carbon compound + oxygen → carbon dioxide + water + energy (complete combustion pattern).',oxidation:'Oxidising agents can convert suitable carbon compounds into more oxidised products.',addition:'Unsaturated compounds can add atoms across multiple bonds.',substitution:'In saturated hydrocarbons, one atom/group can be replaced by another under suitable conditions.'};v.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>o.textContent=m[b.dataset.r])});
document.querySelectorAll('[data-pathway]').forEach(v=>{let steps=v.dataset.steps.split('|'),i=-1,stage=v.querySelector('[data-stage]'),o=v.querySelector('[data-out]');stage.innerHTML=steps.map(s=>`<span>${s}</span>`).join('<i>→</i>');const spans=[...stage.querySelectorAll('span')];v.querySelector('[data-next]').onclick=()=>{i=Math.min(i+1,steps.length-1);spans.forEach((s,j)=>s.classList.toggle('active',j<=i));o.textContent=`Step ${i+1}: ${steps[i]}`};v.querySelector('[data-reset]').onclick=()=>{i=-1;spans.forEach(s=>s.classList.remove('active'));o.textContent='Follow the process in order.'}});
document.querySelectorAll('[data-nerve]').forEach(v=>{const spans=[...v.querySelectorAll('.nervePath span')],o=v.querySelector('[data-out]');v.querySelector('[data-fire]').onclick=()=>{spans.forEach((s,i)=>setTimeout(()=>{s.classList.add('active');o.textContent='Impulse moving: '+s.textContent},i*280));setTimeout(()=>spans.forEach(s=>s.classList.remove('active')),spans.length*280+900)}});
document.querySelectorAll('[data-response]').forEach(v=>{const d=v.querySelector('[data-dir]'),stem=v.querySelector('[data-stem]'),o=v.querySelector('[data-out]');const u=()=>{let x=+d.value;stem.style.transform=`rotate(${x/8}deg)`;o.textContent=x>0?'Growth shown toward the selected positive stimulus direction.':x<0?'Growth shown toward the opposite side.':'No directional bias selected.'};d.oninput=u;u()});
document.querySelectorAll('[data-sequence]').forEach(v=>{const o=v.querySelector('[data-out]'),topic=v.dataset.topic;v.querySelectorAll('[data-n]').forEach((b,i)=>b.onclick=()=>{b.classList.add('revealed');o.textContent=`${topic}: stage ${i+1} revealed. Explain what changes from this stage to the next.`})});
document.querySelectorAll('[data-punnett]').forEach(v=>{const gam=g=>g.length===2?[g[0],g[1]]:[g,g];v.querySelector('[data-build]').onclick=()=>{const a=gam(v.querySelector('[data-p1]').value),b=gam(v.querySelector('[data-p2]').value),cells=[a[0]+b[0],a[0]+b[1],a[1]+b[0],a[1]+b[1]].map(x=>x.split('').sort().join(''));v.querySelector('[data-grid]').innerHTML=cells.map(x=>`<div>${x}</div>`).join('');v.querySelector('[data-out]').textContent='Possible genotype combinations: '+cells.join(', ')}}); 
document.querySelectorAll('[data-heredity]').forEach(v=>{v.querySelector('[data-show]').onclick=()=>{const a=v.querySelector('[data-a]').value,b=v.querySelector('[data-b]').value;v.querySelector('[data-out]').textContent=`Offspring allele pair: ${[a,b].sort().join('')}. Connect genotype with the trait rule used in the lesson.`}});
document.querySelectorAll('[data-optics]').forEach(v=>{const x=v.querySelector('[data-u]'),val=v.querySelector('[data-val]'),img=v.querySelector('[data-img]'),o=v.querySelector('[data-out]'),mode=v.dataset.mode;const u=()=>{let d=+x.value;val.textContent=d;let pos=mode==='mirror'?Math.min(90,72+(30-d)/5):Math.min(90,65+(30-d)/6);img.style.left=pos+'%';img.style.height=(110-d/2)+'px';o.textContent=`Object distance ${d} cm. Move the object and relate the image change to focal length and the chapter ray rules.`};x.oninput=u;u()});
document.querySelectorAll('[data-eye]').forEach(v=>{const d=v.querySelector('[data-distance]'),f=v.querySelector('[data-focus]'),def=v.querySelector('[data-defect]'),o=v.querySelector('[data-out]');const u=()=>{let c=def.value,p=c==='Myopia'?58:c==='Hypermetropia'?74:66;f.style.left=p+'%';o.textContent=`${c}: focus shown qualitatively relative to the retina. Object-distance slider = ${d.value} cm. Correction changes effective convergence.`};d.oninput=u;def.onchange=u;u()});
document.querySelectorAll('[data-colour]').forEach(v=>{const w=v.querySelector('[data-wave]'),o=v.querySelector('[data-out]');const u=()=>{let nm=+w.value,c=nm<450?'violet/blue':nm<500?'blue-green':nm<570?'green/yellow':nm<620?'orange':'red';o.textContent=`Approx. ${nm} nm → ${c} region. Shorter visible wavelengths scatter more strongly in the simple school model.`};w.oninput=u;u()});
document.querySelectorAll('[data-ohm2]').forEach(v=>{const V=v.querySelector('[data-v]'),R=v.querySelector('[data-r]'),o=v.querySelector('[data-out]'),vv=v.querySelector('[data-vv]'),rr=v.querySelector('[data-rr]');const u=()=>{vv.textContent=V.value;rr.textContent=R.value;o.textContent=`I = V/R = ${(+V.value/+R.value).toFixed(2)} A`};V.oninput=u;R.oninput=u;u()});
document.querySelectorAll('[data-resistors]').forEach(v=>{const a=v.querySelector('[data-r1]'),b=v.querySelector('[data-r2]'),o=v.querySelector('[data-out]'),m=v.dataset.mode;const u=()=>{let r1=+a.value,r2=+b.value,re=m==='series'?r1+r2:1/(1/r1+1/r2);o.textContent=`R₁=${r1} Ω, R₂=${r2} Ω → Equivalent ${re.toFixed(2)} Ω (${m})`};a.oninput=u;b.oninput=u;u()});
document.querySelectorAll('[data-electric]').forEach(v=>{const V=v.querySelector('[data-v]'),I=v.querySelector('[data-i]'),o=v.querySelector('[data-out]'),t=v.dataset.topic;const u=()=>{let p=+V.value*+I.value;o.textContent=`V=${V.value} V, I=${I.value} A → P = VI = ${p} W. Use this relationship where appropriate for ${t.replaceAll('-',' ')}.`};V.oninput=u;I.oninput=u;u()});
document.querySelectorAll('[data-magnet]').forEach(v=>{const d=v.querySelector('[data-current]'),ring=v.querySelector('[data-ring]'),o=v.querySelector('[data-out]');v.querySelector('[data-toggle]').onclick=()=>{let up=d.value==='up';ring.textContent=up?'↻':'↺';o.textContent=up?'Current direction selected: apply the relevant right-hand/Fleming rule to get field or force direction.':'Current reversed: the corresponding magnetic/force direction reverses in the qualitative model.'}});
document.querySelectorAll('[data-energy2]').forEach(v=>{const e=v.querySelector('[data-e]'),val=v.querySelector('[data-val]'),p=v.querySelector('[data-pyr]'),o=v.querySelector('[data-out]');const u=()=>{let x=+e.value;val.textContent=x;p.innerHTML=[x,x*.1,x*.01,x*.001].map((n,i)=>`<div style="width:${100-i*18}%">${Math.round(n)} units</div>`).join('');o.textContent='Illustrative 10% energy-transfer model across successive trophic levels.'};e.oninput=u;u()});
document.querySelectorAll('[data-waste]').forEach(v=>{const o=v.querySelector('[data-out]'),m={banana:'Biodegradable — microorganisms can break it down.',paper:'Biodegradable under suitable conditions.',plastic:'Non-biodegradable in the chapter-level classification.',glass:'Non-biodegradable in the chapter-level classification.'};v.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>o.textContent=m[b.dataset.item])});
document.querySelectorAll('[data-ecosystem]').forEach(v=>{let seq=[],o=v.querySelector('[data-out]');v.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{seq.push(b.textContent.trim());o.textContent=seq.join(' → ')})});
